### ISSUE TITLE
Bağış Kabul için Ayar

### ISSUE THREAD

**Issue by ferman2147** [phpuzem/kuveyt#2]
Merhaba, biz dernek sitesinde bağış modülü için Kuveyt Türk Free Pos temin ettik. Sistemi kurduk fakat bağış yapmaya çalışıtığımızda fail sayfasına yönleniyoruz ve herhangi bir hata kodu-mesajı yazdıramıyoruz. Ayrıca Mağaza kodu, Müşteri Numarası, Sipariş Kodu gibi alanlara ne yazacağımız bilemiyoruz. Zira hash hesabına bunlar da katıldığı, ve bizim herhangi bir müşterimiz/mağazamız olmadığı için bizim tarafımızda oluşan hash değeri ile banka tarafında oluşan hash değerinin uyuşmadığı kanaatindeyim. Bununla ilgili nasıl bir düzenleme yapılabilir acaba? Şimdiden teşekkürler, emeğinize sağlık.

**Comment by phpuzem** [comment]
Merhabalar,

Mağaza kodu : Kuveyt tarafından tarafınıza tanımlanır genellikle 4 hane olur. Örn : 1235
Müşteri Numarası : Kuveyt tarafından tarafınıza tanımlanır. Örn : 19200864
Sipariş kodu : Siz tanımlarsınız takip için gerekli olacaktır.

Freepos yapısını inceleyip, yoruma dahil olayım. İyi çalışmalar dilerim.

**Comment by ferman2147** [comment]
Hızlı yanıtınız için çok teşekkür ederim. Ekte inceleyebileceğiniz örnek
php kodu var, bir yardımı olur belki

11 Şubat 2016 10:48 tarihinde Phpuzem <notifications@github.com> yazdı:

**Comment by ferman2147** [comment]
Yaptığım çalışmalar sonucunda sistemin aynı olduğu sonucunda vardım. Sipariş kodunu dediğiniz gibi kendimiz tanımladığımızda bir sonun olmuyor. Kendi kodumu sizin dediğiniz doğrultuda düzenledim ve

> Durum kodu: PosMerchantIPError
Durum mesaji: Kullanici farkli ip ile erismeye çalisiyor.

hatası aldım. Yani response geliyor, sistemsel sıkıntı yok. Bankaya hatayı bildirdim, herhalde IP numarası ile ilgili düzenlemeyi yapıp dönecekler. Sanıyorum bir problem çıkmayacaktır.

**Comment by phpuzem** [comment]
Belirtmekte fayda var kuveyt sistem güvenliği gereği, sanal pos üyeliğinizden sonra server ipsini beklemektedir. Destek mailinden bildirmeniz gerekmektedir. İyi çalışmalar

**Comment by ferman2147** [comment]
Evet haklısınız, IP ile ilgili ayarlamayı yaptılar, ardından sistemi test ettik ve şu an sorunsuz çalışıyor.

**Comment by mavera58** [comment]
Biz bu IP sorununuz çözemedik.Doğru IP girilmesine karşın kuveytturk başka bir ıp tanımladı.Kendi ıp mizi girince ıp hatası aldık.Bankanın kendi girdiği ıp de ise hash data hatası aldık.Çıkamadık işin içinden.
